server:
  port: 8084
spring:
  application:
    name: transactional-outbox
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:demo-db}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:password}
